# Generated by Django 5.2.15 on 2026-07-09 16:36

import apps.customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerprofile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.customers.models.profile_image_upload),
        ),
    ]
