# Generated by Django 5.2.15 on 2026-07-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_providerprofile_business_name'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ProviderService',
            new_name='Service',
        ),
    ]
