@baseUrl = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzNjc1NjA5LCJpYXQiOjE3ODM2NzM4MDksImp0aSI6ImMzMDVkMmU4NWQ3ZTQxNGI5YTYyMmQxMjc5NTIzODQ3IiwidXNlcl9pZCI6IjcxZGQ4OGViLWJiNDEtNGQ1Yy1hODA2LTI4OGQ1YjUwYmQ4ZSJ9.Y_xqH4bNoMbQewjO2BBpKlHpLp3zpmpfwoGwxVhS0ag
@refreshToken = paste_refresh_token_here

###
# Register Customer
POST {{baseUrl}}/api/accounts/register/
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "phone_number": "09056659000",
    "password": "Johndoe123!",
    "confirm_password": "Johndoe123!",
    "first_name": "John",
    "last_name": "Doe",
    "role": "customer"
}

###
# Register Provider
POST {{baseUrl}}/api/accounts/register/
Content-Type: application/json

{
    "email": "janedoe@example.com",
    "phone_number": "09056658000",
    "password": "Janedoe123!",
    "confirm_password": "Janedoe123!",
    "first_name": "Jane",
    "last_name": "Doe",
    "role": "provider"
}

###
# Login
POST {{baseUrl}}/api/accounts/login/
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "Johndoe123!"
}

###
# Me
GET {{baseUrl}}/api/accounts/me/
Authorization: Bearer {{accessToken}}

###
# Refresh Token
POST {{baseUrl}}/api/accounts/token/refresh/
Content-Type: application/json

{
    "refresh": "{{refreshToken}}"
}