@baseUrl = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0MjA3NzgyLCJpYXQiOjE3ODQyMDU5ODIsImp0aSI6IjQxMGIwZTQ1ZmVjMzQ0ODZiYTc3YjBlMWU4ZDQxMWFiIiwidXNlcl9pZCI6IjgwOWExZTUwLTZjZjktNDExZS05ZGExLWJjMThiYTdhZGQ4OSJ9.OpZ2APBxqnnWuhKEYfW0pJp0OaRR2vKe6tJf0OKzA7w
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDgxMDc4MiwiaWF0IjoxNzg0MjA1OTgyLCJqdGkiOiI5MzU3NDNkZGVkNzQ0MDY1YmU0MWExMWEwNDdmM2VkMSIsInVzZXJfaWQiOiI4MDlhMWU1MC02Y2Y5LTQxMWUtOWRhMS1iYzE4YmE3YWRkODkifQ.BWGp0iFmr-GDJpG1pvkWzgcVRLL3SaAKKtEChYhhtS8

###
# Register Customer
POST {{baseUrl}}/api/accounts/register/
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "phone_number": "09056659000",
    "password": "Johndoe123!",
    "confirm_password": "Johndoe123!",
    "first_name": "John",
    "last_name": "Doe",
    "role": "customer"
}

###
# Register Provider
POST {{baseUrl}}/api/accounts/register/
Content-Type: application/json

{
    "email": "thehulk@example.com",
    "phone_number": "09056695000",
    "password": "Thehulk123!",
    "confirm_password": "Thehulk123!",
    "first_name": "Bruce",
    "last_name": "Barner",
    "role": "provider"
}

###
# Login
POST {{baseUrl}}/api/accounts/login/
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "Johndoe123!"
}

###
# Me
GET {{baseUrl}}/api/accounts/me/
Authorization: Bearer {{accessToken}}

###
# Refresh Token
POST {{baseUrl}}/api/accounts/token/refresh/
Content-Type: application/json

{
    "refresh": "{{refreshToken}}"
}