@baseUrl = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzODk2NTY3LCJpYXQiOjE3ODM4OTQ3NjcsImp0aSI6IjU2ODE3YjNmN2M3NjQ0NzBiODNmNDg3M2QzOTEyNDk1IiwidXNlcl9pZCI6IjUwOWJlNDAyLTA1NTgtNDAwZS05NDNmLTc0ZTgyYmY1YzY2ZSJ9.BPXTDKPoNSCp0i_2G3TSPAquIdj1r6tqAqTR64SIb1Q
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDQ5OTU2NywiaWF0IjoxNzgzODk0NzY3LCJqdGkiOiIzZGFiNzRiOGVhYmU0YzVmYTYwNjlhMmU3NjY1ZWFhMiIsInVzZXJfaWQiOiI1MDliZTQwMi0wNTU4LTQwMGUtOTQzZi03NGU4MmJmNWM2NmUifQ.jfzYa0-N9pQRzb0m4gSBtzMfA9_c8UrgkByE18H6OsI

###
# Login
POST {{baseUrl}}/api/accounts/login/
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "Johndoe123!"
}


###
# Refresh Token
POST {{baseUrl}}/api/accounts/token/refresh/
Content-Type: application/json

{
    "refresh": "{{refreshToken}}"
}


###
# Get Customer Profile 
#The lookup field and kwarg is the customer's user_id
GET {{baseUrl}}/api/customers/profile/509be402-0558-400e-943f-74e82bf5c66e/
Authorization: Bearer {{accessToken}}

###
# Update Customer Profile
# Can also update: Phone_no, first_name and last_name
PATCH {{baseUrl}}/api/customers/profile/509be402-0558-400e-943f-74e82bf5c66e/
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "address": "25 Zik's Avenue",
    "city": "Awka",
    "state": "Anambra",
    "first_name": "John"
}