# Generated by Django 5.2.15 on 2026-07-12 00:10

import apps.providers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerverification',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to=apps.providers.models.kyc_image_upload),
        ),
        migrations.AlterField(
            model_name='providerverification',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.providers.models.kyc_image_upload),
        ),
    ]
