# Generated by Django 5.2.15 on 2026-07-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_providerverification_id_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerverification',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
