# Generated by Django 5.2.15 on 2026-07-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_providerverification_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
