# Generated by Django 5.2.15 on 2026-07-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_providerprofile_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
