# Generated by Django 5.2.15 on 2026-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_providerprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='account_name',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='account_number',
            field=models.CharField(blank=True, default='0000000000', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='bank_name',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
    ]
